[package]
name = "flakes"
version = "2.2.26"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
log = { version = "0.4" }
thiserror = { version = "1.0" }

[features]
json = ["serde_json"]
