name: CI-SBOM

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  spdx_creation:
    name: Create Software Bill of Materials
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          sudo apt update && sudo apt install cargo
          cargo install cargo-bom
          cargo install cargo-license
      # flake-ctl
      - name: Run SPDX Creation for flake-ctl
        run: |
          cd flake-ctl
          cargo bom
      - name: Get Dependency Licenses of flake-ctl
        run: |
          cd flake-ctl
          cargo license

      # podman-pilot
      - name: Run SPDX Creation for podman-pilot
        run: |
          cd podman-pilot
          cargo bom
      - name: Get Dependency Licenses of podman-pilot
        run: |
          cd podman-pilot
          cargo license

      # firecracker-pilot
      - name: Run SPDX Creation for firecracker-pilot
        run: |
          cd firecracker-pilot
          cargo bom
      - name: Get Dependency Licenses of firecracker-pilot
        run: |
          cd firecracker-pilot
          cargo license

      # guesttvm-tools
      - name: Run SPDX guesttvm-tools
        run: |
          cd firecracker-pilot/guestvm-tools/sci
          cargo bom
      - name: Get Dependency Licenses guesttvm-tools
        run: |
          cd firecracker-pilot/guestvm-tools/sci
          cargo license
